const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.NinePatch,
		C3.Behaviors.Physics,
		C3.Behaviors.Timer,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layerscale,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Behaviors.Physics.Acts.SetAngularDamping,
		C3.Behaviors.Physics.Acts.SetLinearDamping,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.FadeVolume
	];
};
self.C3_JsPropNameTable = [
	{camera_scale: 0},
	{ScrollTo: 0},
	{Tween: 0},
	{camera: 0},
	{isplaying: 0},
	{win: 0},
	{defeat: 0},
	{cam_scale: 0},
	{gamemanager: 0},
	{Variables: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Mouse: 0},
	{Browser: 0},
	{suelo: 0},
	{flag: 0},
	{xNodo: 0},
	{current_node: 0},
	{BounceX: 0},
	{BounceY: 0},
	{sentido: 0},
	{agregarfuerza: 0},
	{nplayer: 0},
	{fallforce: 0},
	{puedeusar: 0},
	{Physics: 0},
	{Timer: 0},
	{Body: 0},
	{Head: 0},
	{LeftArm: 0},
	{RightArm: 0},
	{LeftLeg: 0},
	{RightLeg: 0},
	{LiteTween: 0},
	{LiteTween2: 0},
	{cannon: 0},
	{Pin: 0},
	{player_masc: 0},
	{Bullet: 0},
	{Rotate: 0},
	{Sine: 0},
	{papelitos: 0},
	{bg: 0},
	{Anchor: 0},
	{Layer: 0},
	{base: 0},
	{fade: 0},
	{tap_to_play: 0},
	{ui_test1: 0},
	{btnReset: 0},
	{btnSound: 0},
	{floor_fx: 0},
	{muzzle: 0},
	{clouds: 0},
	{world_indicator: 0},
	{cloud: 0},
	{test: 0},
	{name: 0},
	{txtTEst: 0},
	{txtUI: 0},
	{saw: 0},
	{star: 0},
	{suelo2: 0},
	{star_particles: 0},
	{Layer2: 0},
	{suelo3: 0},
	{Sine2: 0},
	{saw2: 0},
	{propulsor: 0},
	{spike: 0},
	{Layer3: 0},
	{suelo4: 0},
	{Layer4: 0},
	{suelo5: 0},
	{wall: 0},
	{logo: 0},
	{hand: 0},
	{tuto_colision: 0},
	{Layer5: 0},
	{suelo6: 0},
	{wall2: 0},
	{PlayerBody: 0},
	{Buttons: 0},
	{Suelos: 0},
	{Enemies: 0},
	{Techo: 0},
	{Level: 0},
	{mag: 0},
	{dur: 0},
	{velYPropulsor: 0},
	{vexXFactor: 0},
	{world: 0},
	{newAngle: 0},
	{posX: 0},
	{posY: 0},
	{NewLayer: 0},
	{destino: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0}
];

self.InstanceType = {
	camera: class extends self.ISpriteInstance {},
	gamemanager: class extends self.ISpriteInstance {},
	Variables: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	suelo: class extends self.IWorldInstance {},
	flag: class extends self.IWorldInstance {},
	Body: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	LeftArm: class extends self.ISpriteInstance {},
	RightArm: class extends self.ISpriteInstance {},
	LeftLeg: class extends self.ISpriteInstance {},
	RightLeg: class extends self.ISpriteInstance {},
	cannon: class extends self.ISpriteInstance {},
	player_masc: class extends self.ISpriteInstance {},
	papelitos: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	Layer: class extends self.ISpriteInstance {},
	base: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	tap_to_play: class extends self.ISpriteInstance {},
	ui_test1: class extends self.ISpriteInstance {},
	btnReset: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	floor_fx: class extends self.IWorldInstance {},
	muzzle: class extends self.ISpriteInstance {},
	clouds: class extends self.ISpriteInstance {},
	world_indicator: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	test: class extends self.ISpriteInstance {},
	txtTEst: class extends self.ISpriteFontInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	saw: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	suelo2: class extends self.IWorldInstance {},
	star_particles: class extends self.ISpriteInstance {},
	Layer2: class extends self.ISpriteInstance {},
	suelo3: class extends self.IWorldInstance {},
	saw2: class extends self.ISpriteInstance {},
	propulsor: class extends self.ISpriteInstance {},
	spike: class extends self.ISpriteInstance {},
	Layer3: class extends self.ISpriteInstance {},
	suelo4: class extends self.IWorldInstance {},
	Layer4: class extends self.ISpriteInstance {},
	suelo5: class extends self.IWorldInstance {},
	wall: class extends self.IWorldInstance {},
	logo: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	tuto_colision: class extends self.ISpriteInstance {},
	Layer5: class extends self.ISpriteInstance {},
	suelo6: class extends self.IWorldInstance {},
	wall2: class extends self.IWorldInstance {},
	PlayerBody: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Suelos: class extends self.IWorldInstance {},
	Enemies: class extends self.ISpriteInstance {},
	Techo: class extends self.IWorldInstance {}
}